home/urls.py
from django.urls import path
from .views import home_page,get_emails,my_api

urlpatterns=[
    path('',home_page,name="home_page"),
]

languageleitner/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('vocabs/',include("vocabs.urls")),
    path('accounts/',include("accounts.urls")),
    path('superuserpanel/',include('superuserpanel.urls')),
    path('profile/',include('Profile.urls')),
    path('articles/',include('articles.urls')),
    path('wordcount/',include('wordcount.urls')),
    path('litner/',include('main_logic.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vocabs/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.vocabs_page,name="vocabs_page"),
    path('english/<int:category_id>/',views.english_page,name="english_page"),
    path('english/add/',views.add_english,name="add_english"),
    path('english/edit/<int:vocab_id>/',views.edit_english,name="edit_english"),
    path('english/delete/<int:vocab_id>/',views.delete_english,name="delete_english"),
    path('english/category/',views.category_page,name="category_page"),
    path('english/category/add',views.add_category_english,name="add_category_english"),
]

vocabs/models.py
from django.db import models
from django.contrib.auth.models import User
class english_vocabs(models.Model):
    vocab=models.CharField(max_length=100)
    answer=models.CharField(max_length=100)
    cat=models.ManyToManyField("category_languages",blank=True,null=True)


    def __str__(self):
        return self.vocab

class category_languages(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

vocabs/forms.py
from django import forms

class English_Form(forms.Form):
    word=forms.CharField(max_length=100,widget=forms.TextInput(attrs={"class":"form-control"}))
    answer=forms.CharField(max_length=100,widget=forms.TextInput(attrs={"class":"form-control"}))
    


class Add_Category_Form(forms.Form):
    name=forms.CharField(max_length=100,widget=forms.TextInput(attrs={"class":"form-control"}))

vocabs/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import english_vocabs,category_languages
from .forms import English_Form,Add_Category_Form
from django.contrib.auth.decorators import login_required
@login_required
def vocabs_page(request):
    return render(request,"vocabs_page.html")

def category_page(request):
    ct=category_languages.objects.all()
    print(len(ct))
    context={
        "ct":ct,
    }
    return render(request,"category.html",context)


def add_category_english(request):
    ctfr=Add_Category_Form()
    if request.method=="POST":
        ctfr=Add_Category_Form(data=request.POST)
        if ctfr.is_valid():
            name_t=ctfr.cleaned_data.get('name')
            new_category=category_languages.objects.create(name=name_t)
            new_category.save()
            return redirect('category_page')
    context={
        "ctfr":ctfr,
    }
    return render(request,'add_category_english.html',context)



def english_page(request,category_id):
    if category_id==9:
        vc=english_vocabs.objects.all()
    else:
        vc=category_languages.objects.get(id=category_id).english_vocabs_set.all()
    context={
        "vc":vc,
    }
    return render(request,"english.html",context)


def add_english(request):
    fr=English_Form()
    if request.method=="POST":
        fr=English_Form(data=request.POST)
        if fr.is_valid():
            word_t=fr.cleaned_data.get('word')
            answer_t=fr.cleaned_data.get('answer')
            if english_vocabs.objects.filter(vocab=word_t,answer=answer_t):
                return redirect('category_page')
            else:
                new_word=english_vocabs.objects.create(vocab=word_t,answer=answer_t)
                new_word.save()
                return redirect('category_page')
    context={
        "fr":fr,
    }
    return render(request,'add_english.html',context)

def edit_english(request,vocab_id): 
    vc=english_vocabs.objects.get(id=vocab_id)
    fr=English_Form(initial={"word":vc.vocab,"answer":vc.answer})
    if request.method=="POST":
        fr=English_Form(data=request.POST)
        if fr.is_valid():
            word_t=fr.cleaned_data.get('word')
            answer_t=fr.cleaned_data.get('answer')
            vc.vocab=word_t
            vc.answer=answer_t
            vc.save()
            return redirect('category_page')
    context={
        "fr":fr,
    }
    return render(request,'edit_english.html',context)

def delete_english(request,vocab_id):
    vc=english_vocabs.objects.filter(id=vocab_id)
    vc.delete()
    return redirect('category_page')

vocabs/templates/add_category_english.html
{% extends 'base.html'%}
{% block title%}
    add|Category
{% endblock title%}
{% block content%}
<center>
    <div>
            {% block form%}
            <form style="background-color: #fcd151; border-radius: 5px;width:500px;margin-top:150px;height:300px" method="post">
              {% csrf_token %}
            <h1 style="background-color:#45474b;color:aliceblue;font-size:25pt;height:60px;font-family:Arial, Helvetica, sans-serif;text-align:centers">افزودن کتگوری</h1>
            <div class="mb-3" style="width:400px;margin-top:30px">
                <label for="exampleInputEmail1" class="form-label">کتگوری</label>
                {{ctfr.name}}
            </div>
            <button type="submit" class="btn btn-primary" style="margin-top: 30px;">افزودن</button>
            </form>
            {%endblock form%}
    </div>
</center>
{% endblock content%}

vocabs/templates/add_english.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body style="background-color: #495E57;">
    <div class="collapse" id="navbarToggleExternalContent" data-bs-theme="dark">
        <div class="bg-dark p-4" dir="rtl">
            <ul  dir="rtl" style="list-style-type:none">
                <li  style="color:#F4CE14;float:right;font-family:Arial, Helvetica, sans-serif">
                  <!-- <a dir="rtl" class="nav-link" href="#">خانه</a> -->
                  <a dir="rtl" href="{% url 'home_page' %}" class="link-warning link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">خانه</a>
                </li >
                <li class="nav-item" style="color:#F4CE14;float:right;margin-right:10px;font-family:Arial, Helvetica, sans-serif">
                  <a dir="rtl" href="{% url 'vocabs_page'%}" class="link-warning link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">واژگان</a>
                </li>
                <!-- <li class="nav-item" style="color:#F4CE14;float:right;margin-right:10px">
                  <a dir="rtl" href="#" class="link-warning link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">امکانات</a>
                </li>
                <li class="nav-item" style="color:#F4CE14;float:right;margin-right:10px">
                  <a dir="rtl" href="#" class="link-warning link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">محصولات</a>
                </li> -->
                {% if request.user.is_superuser %}
                <li class="nav-item" style="color:#F4CE14;float:right;margin-right:10px;font-family:Arial, Helvetica, sans-serif">
                  <a dir="rtl" href="{% url 'panel_page'%}" class="link-warning link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">پنل ادمین</a>
                </li>
                {% endif %}
              </ul>
        </div>
    </div>
      <nav class="navbar " style="background-color: #45474B;">
        <!-- Modal
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Login</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body"> 
                <form method="POST">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Username</label>
                    {{fr.username}}
                  </div>
                  <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    {{fr.password}}
                  </div>
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">close</button>
                  <button type="submit" class="btn btn-primary">login</button>
                </form>
              </div>
            </div>
          </div>
        </div> -->
        {% if request.user.is_authenticated%}
        <div>
        <h5 style="color:#F4CE14;margin-left:10px"><a style="text-decoration: none;text-transform:capitalize;font-family:'Times New Roman', Times, serif" href="#">{{request.user}}</a></h5>
      </div>
      <div style="margin-right:1200px;padding-bottom:8px;font-family:Arial, Helvetica, sans-serif">
        <a href="{% url 'logout_page'%}" class="link-warning link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">خروج</a> 
      </div>
        {% else %}
        <div style="float: left;margin-left:10px" >
            <a href="{% url 'login_page' %}"><button type="button"  class="btn btn-outline-warning" dir="rtl" style="border-color:#F4CE14;font-family:Arial, Helvetica, sans-serif;font-weight:bold">ورود</button></a>
            <a href="{% url 'signup_page' %}"><button type="button" class="btn btn-outline-warning" dir="rtl" style="border-color:#F4CE14 ;font-family:Arial, Helvetica, sans-serif;font-weight:bold">ثبت نام</button></a>
          </div>
        {% endif %}
        <center>
        <div style="margin-right: 120px;">
          <!--LOGO-->
            <!-- <img style="border-radius:120px;padding-top:20px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk9IdfBve_C745O4RGJ61eWwecVPOx8sJliQ&s" width="60px" alt=""> -->
        </div>
        </center>
        <div>
            <div class="container-fluid" >
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#F4CE14" class="bi bi-list" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
                  </svg>
            </button>
         </div>
        </div>
      </nav>
      <center>
        {% block form%}
        <form style="background-color: #fcd151; border-radius: 5px;width:500px;margin-top:150px;height:300px" method="post">
          {% csrf_token %}
        <h1 style="background-color:#45474b;color:aliceblue;font-size:25pt;height:60px;font-family:Arial, Helvetica, sans-serif;text-align:centers">افزودن واژه</h1>
        <div class="mb-3" style="width:400px">
            <label for="exampleInputEmail1" class="form-label">واژه</label>
            {{fr.word}}
        </div>
        <div class="mb-3" style="width:400px">
            <label for="exampleInputPassword1" class="form-label">معنی</label>
            {{fr.answer}}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        {%endblock form%}
    </center>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

vocabs/templates/category.html
{% extends 'base.html' %}
{% block content%}
<center>
  <div style="width: 1000px;margin-top:50px">
    <h1 style="color:#45474b">Category</h1>
    <ul class="dropdown-menu d-block position-static mx-0 shadow w-220px" data-bs-theme="light">
      {% for i in ct%}
      <li>
        <a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'english_page' i.id%}">
          <svg class="bi" width="16" height="16"><use xlink:href="#files"></use></svg>
          {{i.name}}
        </a>
      </li>
      {% endfor %}
      <li><hr class="dropdown-divider"></li>
      <li>
        <a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'english_page' 9 %}">
          <svg class="bi" width="16" height="16"><use xlink:href="#files"></use></svg>
          All Vocabs
        </a>
      </li>
    </ul>
  </div>
  {% if perms.vocabs.add_category_languages%}
  <div style="margin-top:20px">
    <a href="{% url 'add_category_english' %}"><button type="button" class="btn btn-outline-secondary" style="font-family:Arial, Helvetica, sans-serif">افزودن کتگوری</button></a>
  </div>
  {% endif %}
</center>
{% endblock content%}

vocabs/templates/edit_english.html
{% extends 'add_english.html'%}
{% block form%}
<form style="background-color: #fcd151; border-radius: 5px;width:500px;margin-top:150px;height:300px" method="post">
    {% csrf_token%}
    <h1 style="background-color:#45474b;color:aliceblue;font-size:25pt;height:60px;font-family:Arial, Helvetica, sans-serif;text-align:centers">ویرایش واژه</h1>
    <div class="mb-3" style="width:400px">
        <label for="exampleInputEmail1" class="form-label">واژه</label>
        {{fr.word}}
    </div>
    <div class="mb-3" style="width:400px">
        <label for="exampleInputPassword1" class="form-label">معنی</label>
        {{fr.answer}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock form%}

vocabs/templates/vocabs_page.html
{% extends 'base.html' %}
{% block content %}
<div>
    <center>
    <div style="width:700px">
        <div class="row" style="margin-top:100px">
            <div class="col"><a href="{% url 'category_page' %}"><button type="button" class="btn btn-outline-secondary" style="font-family:Arial, Helvetica, sans-serif;">انگلیسی</button></a></div>
            <div class="col"><a href="" class="nav-item nav-link disabled"><button type="button" class="btn btn-outline-secondary disabled" style="font-family:Arial, Helvetica, sans-serif;">فارسی</button></a></div>
            <div class="col"><a href="" class="nav-item nav-link disabled"><button type="button" class="btn btn-outline-secondary disabled" style="font-family:Arial, Helvetica, sans-serif;">عربی</button></a></div>
            <div class="col"><a href="" class="nav-item nav-link disabled"><button type="button" class="btn btn-outline-secondary disabled" style="font-family:Arial, Helvetica, sans-serif;">آلمانی</button></a></div>
        </div>
        <!-- <div class="row" style="margin-top:50px">
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
        </div>
        <div class="row" style="margin-top:50px">
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
        </div>
        <div class="row" style="margin-top:50px">
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
        </div>
        <div class="row" style="margin-top:50px">
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
        </div>
        <div class="row" style="margin-top:50px">
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
            <div class="col"><button type="button" class="btn btn-outline-secondary">Secondary</button></div>
        </div> -->
    </div>
    </center>
</div>
{% endblock content %}