articles/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.articles_page,name="articles_page"),
    path('article/<int:id>/',views.detals_articles,name='detail_page')
]

home/urls.py
from django.urls import path
from .views import home_page,get_emails,my_api

urlpatterns=[
    path('',home_page,name="home_page"),
]

languageleitner/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('vocabs/',include("vocabs.urls")),
    path('accounts/',include("accounts.urls")),
    path('superuserpanel/',include('superuserpanel.urls')),
    path('profile/',include('Profile.urls')),
    path('articles/',include('articles.urls')),
    path('wordcount/',include('wordcount.urls')),
    path('litner/',include('main_logic.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
choices_custom={
    "d":"draft",
    "p":"published",
}
class Articles_page(models.Model):
    title=models.CharField(max_length=100,default="")
    short_description=models.TextField()
    description=models.TextField()
    image=models.ImageField(upload_to='media/images/')
    author_name=models.CharField(max_length=100)
    category=models.ManyToManyField("Category_Articles",blank=True,null=True)
    published=models.CharField(max_length=100,choices=choices_custom,default="p")
    created_date=models.DateTimeField(default=datetime.datetime.today)
    def __str__(self):
        return self.title
    

class Category_Articles(models.Model):
    name=models.CharField(max_length=100)
    published=models.BooleanField(default=True)
    def __str__(self):
        return self.name
    
class ArticlesComment(models.Model):
    article=models.ForeignKey(Articles_page,on_delete=models.CASCADE,verbose_name="مقاله")
    parent=models.ForeignKey('ArticlesComment',on_delete=models.CASCADE,verbose_name="والد",null=True,blank=True)
    text=models.TextField(verbose_name="متن")
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="کاربر")   
    created_date=models.DateTimeField(auto_now_add=True,verbose_name="زمان ساخت")

    class Meta:
        verbose_name="کامنت مقاله"
        verbose_name_plural="کامنت مقالات"


    def __str__(self):
        return f'{self.user}'

articles/views.py
from django.shortcuts import render,redirect
from .models import Articles_page,ArticlesComment,Category_Articles
from django.core.paginator import Paginator
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import ArticlesSerializers
from rest_framework import status
def articles_page(request):
    categorys=Category_Articles.objects.all()
    if request.GET.get('category'):
        category_title=request.GET.get('category')
        articles=Articles_page.objects.filter(published='p',category__name=category_title)
    else:
        articles=Articles_page.objects.filter(published='p')
    articles_paginate=Paginator(articles,6)
    page_number = request.GET.get("page")
    page_obj = articles_paginate.get_page(page_number)
    context={
        "articles":page_obj,
        "categorys":categorys,
    }
    return render(request,'articles_page.html',context)


def detals_articles(request,id):
    ar=Articles_page.objects.get(id=id)
    if request.method=="POST":
        comment_email=request.POST.get('email_commment')
        new_comment=ArticlesComment.objects.create(article=ar,parent=None,text=comment_email,user=request.user)
        new_comment.save()
        return redirect('detail_page',id=id)
    comment=ArticlesComment.objects.filter(article__id=id,parent=None).prefetch_related('articlescomment_set')
    context={
        "article":ar,
        "comments":comment,
    }
    return render(request,"detailpage.html",context)

@api_view(['GET',"POST"])
def api_articles(request):
    if request.method=="GET":
        articles=Articles_page.objects.all()
        serializers=ArticlesSerializers(articles,many=True)
        return Response(serializers.data)
    elif request.method=="POST":
        serializer=ArticlesSerializers(data=request.data)
        if serializer.is_valid():
            title=serializer.validated_data.get('title')
            short_description=serializer.validated_data.get('short_description')
            image=serializer.validated_data.get('image')
            author_name=serializer.validated_data.get('author_name')
            description=serializer.validated_data.get('description')
            published=serializer.validated_data.get('published')
            created_date=serializer.validated_data.get('created_date')
            articles_new=Articles_page.objects.create(title=title,short_description=short_description,image=image,author_name=author_name,description=description,published=published,created_date=created_date)
            category=request.data.get('category')
            for category_id in category:
                cat=Articles_page.objects.get(id=category_id)
                articles_new.category.add(cat)
            return Response(request.data,status=status.HTTP_201_CREATED)
        return Response(status=status.HTTP_400_BAD_REQUEST)

articles/templates/articles_page.html
{% extends 'base.html' %}
{% load jalali_tags %}
{% block title%}
لایت باکس | مقالات آموزشی
{% endblock title %}
{% block content%}
<!-- Page Title -->
<div style="direction: rtl;">
<div class="page-title" data-aos="fade">
  <div class="container">
    <nav class="breadcrumbs">
      <ol>
        <li><a href="{% url 'home_page' %}">خانه</a></li>
        <li class="current">مقالات آموزشی</li>
      </ol>
    </nav>
    <h1>بلاگ آموزشی</h1>
  </div>
</div><!-- End Page Title -->

<div class="container">
  <div class="row">

    <div class="col-lg-8" >

      <!-- Blog Posts Section -->
      <section id="blog-posts" class="blog-posts section" >

        <div class="container">

          <div class="row gy-4" >

            {% for article in articles %}
            <div class="col-lg-12" style="border-radius: 30px;">
              <article>

                <div class="post-img">
                  <img width="1000px" src="{{article.image.url}}" alt="" class="img-fluid">
                </div>

                <h2 class="title">
                  <a href="blog-details.html">{{article.title}}</a>
                </h2>

                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-details.html">{{article.author_name}}</a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-details.html"><time datetime="2022-01-01"> {{ article.created_date|to_jalali:'%y/%m/%d' }}</time></a></li>
                    <!-- <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-details.html">12 Comments</a></li> -->
                  </ul>
                </div>

                <div class="content">
                  <p>
                    {{article.short_description}}
                  </p>

                  <div class="read-more">
                    <a href="{% url 'detail_page' article.id%}">جزییات مقاله</a>
                  </div>
                </div>

              </article>
            </div><!-- End post list item -->
            {% endfor %}

          </div><!-- End blog posts list -->

        </div>

      </section><!-- /Blog Posts Section -->

      <!-- Blog Pagination Section -->
      <section id="blog-pagination" class="blog-pagination section">

        <div class="container">
          <div class="d-flex justify-content-center">
            <ul>
              {% if articles.has_previous %}
                <li><a href="?page={{ articles.previous_page_number}} "><</a></li>
              {% endif %}
              {% for i in articles.paginator.page_range %}
                {% if articles.number == i %}
                <li><a href="?page={{i}}" class="active">{{i}}</a></li>
                {% else %}
                <li><a href="?page={{i}}" >{{i}}</a></li>
                {% endif %}
              {% endfor %}
              {% if articles.has_next %}
                <li><a href="?page={{ articles.next_page_number }}">&#62;</a></li>
              {% endif %}
              
              <!-- <li><a href="#">1</a></li>
              <li><a href="#" class="active">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li>...</li>
              <li><a href="#">10</a></li>-->
            </ul>
          </div>
        </div>

      </section><!-- /Blog Pagination Section -->

    </div>

    <div class="col-lg-4 sidebar">

      <div class="widgets-container">

        <!-- Search Widget -->
        <!-- <div class="search-widget widget-item">

          <h3 class="widget-title">Search</h3>
          <form action="">
            <input type="text">
            <button type="submit"><i class="bi bi-search"></i></button>
          </form>

        </div>/Search Widget -->

        <!-- Categories Widget -->
        <div class="categories-widget widget-item">

          <h3 class="widget-title">دسته بندی ها</h3>
          <ul class="mt-3">
            {% for category in categorys %}
              <li><a href="?category={{category.name}}">{{category.name}} <span>({{category.articles_page_set.count}})</span></a></li>
            {% endfor %}
          </ul>
        </div><!--/Categories Widget -->

        <!-- Recent Posts Widget -->
        <!-- <div class="recent-posts-widget widget-item">

          <h3 class="widget-title">Recent Posts</h3>

          <div class="post-item">
            <img src="assets/img/blog/blog-recent-1.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Nihil blanditiis at in nihil autem</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div> End recent post item-->

          <!-- <div class="post-item">
            <img src="assets/img/blog/blog-recent-2.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Quidem autem et impedit</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div>End recent post item

          <div class="post-item">
            <img src="assets/img/blog/blog-recent-3.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Id quia et et ut maxime similique occaecati ut</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div>End recent post item -->

          <!-- <div class="post-item">
            <img src="assets/img/blog/blog-recent-4.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Laborum corporis quo dara net para</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div>End recent post item -->

          <!-- <div class="post-item">
            <img src="assets/img/blog/blog-recent-5.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Et dolores corrupti quae illo quod dolor</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div>End recent post item -->

        <!-- </div>/Recent Posts Widget -->

        <!-- Tags Widget -->
        <!-- <div class="tags-widget widget-item">

          <h3 class="widget-title">Tags</h3>
          <ul>
            <li><a href="#">App</a></li>
            <li><a href="#">IT</a></li>
            <li><a href="#">Business</a></li>
            <li><a href="#">Mac</a></li>
            <li><a href="#">Design</a></li>
            <li><a href="#">Office</a></li>
            <li><a href="#">Creative</a></li>
            <li><a href="#">Studio</a></li>
            <li><a href="#">Smart</a></li>
            <li><a href="#">Tips</a></li>
            <li><a href="#">Marketing</a></li>
          </ul>

        </div>/Tags Widget -->

      </div>

    </div>

  </div>
</div>
</div>
{% endblock content%}

articles/templates/detailpage.html
{% extends 'base.html'%}
{% load jalali_tags %}
{% block title%}
مقاله {{article.title}}
{% endblock title%}
{% block content%}
<div style="direction: rtl;">
<!-- Page Title -->
<div class="page-title" data-aos="fade">
  <div class="container">
    <nav class="breadcrumbs">
      <ol>
        <li><a href="{% url 'home_page' %}">خانه</a></li>
        <li><a href="{% url 'articles_page' %}">مقالات آموزشی</a></li>
        <li class="current">جزییات مقاله</li>
      </ol>
    </nav>
    <h1>جزییات مقاله</h1>
  </div>
</div><!-- End Page Title -->

<div class="container">
  <div class="row">

    <div class="col-lg-8">

      <!-- Blog Details Section -->
      <section id="blog-details" class="blog-details section">
        <div class="container">

          <article class="article">

            <div class="post-img">
              <img src="assets/img/blog/blog-1.jpg" alt="" class="img-fluid">
            </div>

            <h2 class="title">{{article.title}}</h2>

            <div class="meta-top">
              <ul>
                <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-details.html">{{article.author_name}}</a></li>
                <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-details.html"><time datetime="2020-01-01">{{ article.created_date|to_jalali:'%y/%m/%d' }}</time></a></li>
                <!-- <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-details.html">12 Comments</a></li> -->
              </ul>
            </div><!-- End meta top -->

            <div class="content">
              <p>
                {{article.description}}
              </p>

              <!-- <p>
                Sit repellat hic cupiditate hic ut nemo. Quis nihil sunt non reiciendis. Sequi in accusamus harum vel aspernatur. Excepturi numquam nihil cumque odio. Et voluptate cupiditate.
              </p>

              <blockquote>
                <p>
                  Et vero doloremque tempore voluptatem ratione vel aut. Deleniti sunt animi aut. Aut eos aliquam doloribus minus autem quos.
                </p>
              </blockquote>

              <p>
                Sed quo laboriosam qui architecto. Occaecati repellendus omnis dicta inventore tempore provident voluptas mollitia aliquid. Id repellendus quia. Asperiores nihil magni dicta est suscipit perspiciatis. Voluptate ex rerum assumenda dolores nihil quaerat.
                Dolor porro tempora et quibusdam voluptas. Beatae aut at ad qui tempore corrupti velit quisquam rerum. Omnis dolorum exercitationem harum qui qui blanditiis neque.
                Iusto autem itaque. Repudiandae hic quae aspernatur ea neque qui. Architecto voluptatem magni. Vel magnam quod et tempora deleniti error rerum nihil tempora.
              </p>

              <h3>Et quae iure vel ut odit alias.</h3>
              <p>
                Officiis animi maxime nulla quo et harum eum quis a. Sit hic in qui quos fugit ut rerum atque. Optio provident dolores atque voluptatem rem excepturi molestiae qui. Voluptatem laborum omnis ullam quibusdam perspiciatis nulla nostrum. Voluptatum est libero eum nesciunt aliquid qui.
                Quia et suscipit non sequi. Maxime sed odit. Beatae nesciunt nesciunt accusamus quia aut ratione aspernatur dolor. Sint harum eveniet dicta exercitationem minima. Exercitationem omnis asperiores natus aperiam dolor consequatur id ex sed. Quibusdam rerum dolores sint consequatur quidem ea.
                Beatae minima sunt libero soluta sapiente in rem assumenda. Et qui odit voluptatem. Cum quibusdam voluptatem voluptatem accusamus mollitia aut atque aut.
              </p> -->
              <img src="{{article.image.url}}" class="img-fluid" alt="">

              <!-- <h3>Ut repellat blanditiis est dolore sunt dolorum quae.</h3>
              <p>
                Rerum ea est assumenda pariatur quasi et quam. Facilis nam porro amet nostrum. In assumenda quia quae a id praesentium. Quos deleniti libero sed occaecati aut porro autem. Consectetur sed excepturi sint non placeat quia repellat incidunt labore. Autem facilis hic dolorum dolores vel.
                Consectetur quasi id et optio praesentium aut asperiores eaque aut. Explicabo omnis quibusdam esse. Ex libero illum iusto totam et ut aut blanditiis. Veritatis numquam ut illum ut a quam vitae.
              </p>
              <p>
                Alias quia non aliquid. Eos et ea velit. Voluptatem maxime enim omnis ipsa voluptas incidunt. Nulla sit eaque mollitia nisi asperiores est veniam.
              </p>

            </div>End post content-->

            <div class="meta-bottom">
              <i class="bi bi-folder"></i>
              {% for category in article.category.all%}
                <ul class="cats">
                  <li><a href="#">{{category.name}}</a></li>
                </ul>
                {% endfor %}

              <!-- <i class="bi bi-tags"></i>
              <ul class="tags">
                <li><a href="#">Creative</a></li>
                <li><a href="#">Tips</a></li>
                <li><a href="#">Marketing</a></li>
              </ul>
            </div>End meta bottom -->

          </article>

        </div>
      </section><!-- /Blog Details Section -->

      <!-- Blog Author Section -->
      <section id="blog-author" class="blog-author section">

        <div class="container">
          <div class="author-container d-flex align-items-center">
            <img src="assets/img/blog/blog-author.jpg" class="rounded-circle flex-shrink-0" alt="">
            <div>
              <h4>نویسنده: {{article.author_name}}</h4>
              <!-- <div class="social-links">
                <a href="https://x.com/#"><i class="bi bi-twitter-x"></i></a>
                <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
              </div> -->
              <!-- <p>
                Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
              </p> -->
            </div>
          </div>
        </div>

      </section><!-- /Blog Author Section -->

      <!-- Blog Comments Section -->
      <section id="blog-comments" class="blog-comments section">

        <div class="container">

          <h4 class="comments-count">کامنت( {{comments.count|upper}} )</h4>

        {% for comment in comments%}
          <div id="comment-1" class="comment">
            <div class="d-flex">
              <div class="comment-img"><img src="assets/img/blog/comments-1.jpg" alt=""></div>
              <div>
                <h5><a href="">{{comment.user}}</a> <a href="#" class="reply"></a></h5>
                <time datetime="2020-01-01">{{comment.created_date|to_jalali}}</time>
                <p>
                  {{comment.text}}
                </p>
              </div>
            </div>
          </div>
          {% for cm in comment.articlescomment_set.all %}
              <div id="comment-1" class="comment" style="margin-right:50px">
                <div class="d-flex">
                  <div class="comment-img"><img src="assets/img/blog/comments-1.jpg" alt=""><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
                  </svg>پاسخ</div>
                  <div>
                    <h5><a href="">{{cm.user}}</a> <a href="#" class="reply"></a></h5>
                    <time datetime="2020-01-01">{{cm.created_date|to_jalali}}</time>
                    <p>
                      {{cm.text}}
                    </p>
                  </div>
                </div>
              </div>
          {% endfor %}
        {% endfor %}

        </div>

      </section><!-- /Blog Comments Section -->

      <!-- Comment Form Section -->
       {% if request.user.is_authenticated %}
      <section id="comment-form" class="comment-form section">
        <div class="container">

          <form action="{% url 'detail_page' article.id%}" method="post">
            {% csrf_token %}
            <h4>کامنت</h4>
            <div class="row">
              <div class="col form-group">
                <textarea  class="form-control" placeholder="نظر شما" name="email_commment"></textarea>
              </div>
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary">ثبت نظر</button>
            </div>

          </form>

        </div>
      </section><!-- /Comment Form Section -->
      {% else %}
      <h3>برای ثبت نظر وارد <a href="{% url 'login_page' %}">حساب کاربری</a> خود شوید</h3>
      {% endif %}

    </div>

    <!-- <div class="col-lg-4 sidebar">

      <div class="widgets-container">

        Search Widget
        <div class="search-widget widget-item">

          <h3 class="widget-title">Search</h3>
          <form action="">
            <input type="text">
            <button type="submit" title="Search"><i class="bi bi-search"></i></button>
          </form>

        </div>/Search Widget

        Categories Widget
        <div class="categories-widget widget-item">

          <h3 class="widget-title">دسته بندی ها</h3>
          <ul class="mt-3">
            {% for category in categorys%}
              <li><a href="?category={{category.name}}">{{category.name}} <span>({{category.articles_page_set.count}})</span></a></li>
            {% endfor %}
          </ul>
        </div>Categories Widget

        Recent Posts Widget
        <div class="recent-posts-widget widget-item">

          <h3 class="widget-title">Recent Posts</h3>

          <div class="post-item">
            <img src="assets/img/blog/blog-recent-1.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Nihil blanditiis at in nihil autem</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div> End recent post item

          <div class="post-item">
            <img src="assets/img/blog/blog-recent-2.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Quidem autem et impedit</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div> End recent post item

          <div class="post-item">
            <img src="assets/img/blog/blog-recent-3.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Id quia et et ut maxime similique occaecati ut</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div> End recent post item

          <div class="post-item">
            <img src="assets/img/blog/blog-recent-4.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Laborum corporis quo dara net para</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div>End recent post item 

          <div class="post-item">
            <img src="assets/img/blog/blog-recent-5.jpg" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Et dolores corrupti quae illo quod dolor</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div>End recent post item 

        </div>Recent Posts Widget

        Tags Widget
         <div class="tags-widget widget-item">

          <h3 class="widget-title">Tags</h3>
          <ul>
            <li><a href="#">App</a></li>
            <li><a href="#">IT</a></li>
            <li><a href="#">Business</a></li>
            <li><a href="#">Mac</a></li>
            <li><a href="#">Design</a></li>
            <li><a href="#">Office</a></li>
            <li><a href="#">Creative</a></li>
            <li><a href="#">Studio</a></li>
            <li><a href="#">Smart</a></li>
            <li><a href="#">Tips</a></li>
            <li><a href="#">Marketing</a></li>
          </ul>

        </div>/Tags Widget 

      </div>

    </div> -->

  </div>
</div>
</div>
{% endblock content%}